var GAME_LEVELS = [
  ["xx                                                                              ",
   "xx                                                           o                  ",
   "xx                                          o                o                  ",
   "xx                                          o                o                  ",
   "xx                                                                              ",
   "xx                                         xxx                                  ",
   "xx                             o                                x x             ",
   "xx                             o                               x!x!x            ",
   "xx                                                       xxxxxx!!!!!x    x      ",
   "xx                                   xxx                       x!!!x            ",
   "xx                                                              x!x             ",
   "xx                        xxxxx                  xx              v              ",
   "xx                        xxxxx                                              x  ",
   "xx                        xxxxx                                            o    ",
   "xx                   xxxxxxxxxx              x                             o    ",
   "xx                   xxxxxxxxxx                                                 ",
   "xx               xxxxxxxxxxxxxx          o                                xxxxxx",
   "xx     @         xxxxxxxxxxxxxx          o                    xx          xxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        xxxx        xxxxxx           xxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["xxxxx    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                              ",
   "xxxxx @  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                    xxxxxxxxx                                 ",
   "xxxxx    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                      ooooo x                                 ",
   "xxxxx    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                      ooooo x                                 ",
   "xxxxx    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                   xxxxxxxxxx       xxxxxxxxxxxxxxxxxxxxxxxxx ",
   "xxxxx    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        x               x!!x        xx             o  o  o  x ",
   "xxxxx    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                        x!!x        x    o                  x ",
   "xxxxx    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                       xvvx        x    o     xxxxxxxxxxxxxx ",
   "xxxxx    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!x                                  xx                  xxxxx ",
   "xxxxx    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!x                                 xxxxx                 xxx ",
   "xxxxx                                   x!x      xx       o                  xxxxxxxxxxxxx     o    xx ",
   "xxxxx                                    v                o                  xxxxxxxxxxxx          xx  ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                           xxxxxxxx             xxx  ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                   xxxxxxxxxx             xxxxxx           xxxxxx   ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                 xxxxxxxxxxxxx                       xxxxxxxxxxx    ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            xxxxxxxxxxxxxxxxxxx                    xxxxxxxxx       ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx               o   o   o   o  xxxx              xxxxxxxxxx     o   ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx         x  o   o   o   o    xxxxx                            o   ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                     o   ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx               xxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxvxvxvx                             o xx              xxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                    xxxxx   xxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxvvxxxxvvxxxxvvxxxxvvxxxx                                             xxxxxxxxxxxxxxxxxxxxx",
   "                                                                                  xxxxxxxxxxxxxxxxxxxxx",
   "                                                       xxxxxxxxssssssxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                     xxxxxxxxxxxxxxxxxx",
   "     d                                                               o  o  o  o  o   xxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "   @                                                                                                           ",
   "                                                                                                              ",
   "                        x     x     x     x                                                                       ",
   "               x
   "  xxxx
   "
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
