var GAME_LEVELS = [
  ["xx                                                                              ",
   "xx                                                           o                  ",
   "xx                                          o                o                  ",
   "xx                                          o                o                  ",
   "xx                                                                              ",
   "xx                                         xxx                                  ",
   "xx                             o                                x x             ",
   "xx                             o                               x!x!x            ",
   "xx                                                       xxxxxx!!!!!x    x      ",
   "xx                                   xxx                       x!!!x            ",
   "xx                                                              x!x             ",
   "xx                        xxxxx                  xx              v              ",
   "xx                        xxxxx                                              x  ",
   "xx                        xxxxx                                            o    ",
   "xx                   xxxxxxxxxx              x                             o    ",
   "xx                   xxxxxxxxxx                                                 ",
   "xx               xxxxxxxxxxxxxx          o                                xxxxxx",
   "xx     @         xxxxxxxxxxxxxx          o                    xx          xxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        xxxx        xxxxxx           xxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["xxxxx    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                              ",
   "xxxxx @  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                    xxxxxxxxx                                 ",
   "xxxxx    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                      ooooo x                                 ",
   "xxxxx    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                      ooooo x                                 ",
   "xxxxx    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx              x     xxxxxxxxxx       xxxxxxxxxxxxxxxxxxxxxxxx ",
   "xxxxx    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        x               x!!x        xx             o  o  o  x ",
   "xxxxx    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                        x!!x        x    o                  x ",
   "xxxxx    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                     xvvx        x    o     xxxxxxxxxxxxxx ",
   "xxxxx    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!x                                 xxx                 xxxxx ",
   "xxxxx    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!x                                 xxxxx                 xxx ",
   "xxxxx                                  x!!!x     xx       o                  xxxxxxxxxxxxx     o   xxx ",
   "xxxxx                                    v                o                  xxxxxxxxxxxx          xx  ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                           xxxxxx               xxx  ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                   xxxxxxxxxx             xxx              xxxxxx   ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                 xxxxxxxxxxxxx                       xxxxxxxxxxx    ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx             xxxxxxxxxxxxxxxxxx                    xxxxxxxxx       ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx               o   o   o   o  xxxx             xxxxxxxxxxx     o   ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx         x  o   o   o   o    xxxxx                            o   ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                    o   ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!x                                 x              xxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                               o x              xxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!v v v x                              xxxx   xxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxvvxxxxvvxxxxvvxxxxvvxxxx                                             xxxxxxxxxxxxxxxxxxxxx",
   "                                                                                  xxxxxxxxxxxxxxxxxxxxx",
   "                                                           xxxxxxxxssxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                       o   o   o     xxxxxxxxxxxxxxxxxx",
   "     p                                                               o   o   o   o   xxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                               v          v           v             v   v   v   v      v   v                                v    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                                                                                                                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                                                                                                                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     v           v                           ",
   "                                               o                                                                                                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                             ",
   "                                                                                                                                                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                             ",
   "                                                                                                                                            o    xxxxxxx                                                                                                                  ",
   "   @                                                                                                                                       xxxxxxx                                                                                                                        ",
   "                        o           o                         o                     o                 o                                                   o              o                      o                                       o             o o o          o p  ",
   "                        x     x     x     x         x         x          x     xxxxxxxxxxxxxxxx    xxxxxxxxxxxxxxxx        o                                                                        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "               x                                                                                                       xxxxxxxxxxxx     xxxxxxxxxxxxxxxx     xxxxxxxxxxx    xxxxxxxxxxxxxxxxxxxxxxxx                                                                      ",
   "  xxxx                                                                                                                                                                                                                                                                    ",
   "                                                                                                                                                                                                                                                                          ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],

  ["                                                          ",
   "              z    z    zzzzz    z   z                    ",
   "              z    z    z   z    z   z                    ",
   "               zzzzz    z   z    z   z                    ",
   "                   z    z   z    z   z                    ",
   "               zzzz     zzzzz    zzzzz                    ",
   "                                                          ",
   "                                                          ",
   "           z       z   zzzzz   zz    z     zz             ",                  
   "           z       z     z     z z   z    zzzz            ",               
   "           z   z   z     z     z  z  z     zz             ", 
   "           z  z z  z     z     z   z z                    ",
   "            zz   zz    zzzzz   z    zz     zz             ",           
   "                                                          ",
   "                                                          ",
   "                           @                              ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
